version: "3.8"

services:
  app:
    build: ../clearing-house-app/
    environment:
      NODE_ENV: production

  edc:
    build: ../clearing-house-edc/launchers/connector-prod/
    environment:
      NODE_ENV: production