# This is a basic workflow to help you get started with Actions

name: Deploy to Github-Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: mdBook Action
        uses: peaceiris/actions-mdbook@v1

      - name: Install D2 (Diagram generator)
        run: curl -fsSL https://d2lang.com/install.sh | sh -s --

      - name: Install mdbook-d2 integration
        run: cargo install mdbook-d2 --locked
        
      - name: Build book
        run: mdbook build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book

permissions:
  contents: write
