name: test

on:
  pull_request:
    branches:
      - master
      - beta
      - alpha
      - development


jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and Test
      run: |
        cd clearing-house-app
        cargo build --verbose
        cargo test --verbose
